name: events_app_user
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-408.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  get: ^4.6.5
  get_time_ago: ^1.2.2
  image_picker: ^0.8.7+5
  shimmer: ^2.0.0
  intl: ^0.18.1
  zoom_tap_animation: ^1.1.0
  iconly: ^1.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#424750"
  #background_image: "assets/images/logo_app.png"
  image:  "assets/images/logo_app.png"
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/en_US.json
    - assets/lang/pt_BR.json
    - assets/lang/de_DE.json

  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 700

flutter_icons: 
  image_path: "assets/images/icon_launcher.png"
  android: true
  ios: true